In [1]:
import numpy as np

In [97]:
escalar = 5.679
vector= np.array([1,2,3])
matriz=np.array([[1,2],[3,4],[5,6]])
tensor = np.array ([
[[1,2,3], [4, 5,6], [6,7,8]],
[[11,12,13],[14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]],
])

In [70]:
print(escalar)

5.679


In [71]:
escalar.shape

AttributeError: 'float' object has no attribute 'shape'

In [72]:
vector.shape

(3,)

In [73]:
print(vector)

[1 2 3]


In [74]:
len(vector)

3

In [75]:
matriz.shape#usar shape en vez de lenght

(2, 2)

In [76]:
print(matriz)

[[1 2]
 [3 4]]


In [77]:
len(matriz)

2

In [78]:
print(matriz.size)

4


In [79]:
print(tensor.shape)

(3, 3, 3)


In [80]:
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 6  7  8]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [81]:
print(tensor.size)

27


In [82]:
#Challenge´s class

In [64]:
vectorChallenge= np.array([8,2,3,9,8,7,10])
matrixChallenge=np.array([[1,2,4,6,5,10],[7,8,9,10,78,3]])
tensorChallenge = np.array ([
[[1,2,3], [4, 5,6], [6,7,8]],
[[11,12,13],[14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]],
])

In [56]:
print(vectorChallenge.size)

7


In [57]:
print(matrixChallenge.shape)

(2, 6)


In [60]:
print(vectorChallenge.shape)

(7,)


In [66]:
print(tensorChallenge.size)

27


In [67]:
print(tensorChallenge.shape)

(3, 3, 3)


In [83]:
#Transpositions#

In [84]:
escalar_t=escalar.t

AttributeError: 'float' object has no attribute 't'

In [90]:
vector_t=vector.T
print("Array with none transposition:",vector)
print("Array with transposition:",vector_t)

First with not transposition: [1 2 3]
Second with transposition: [1 2 3]


In [98]:
matriz_t=matriz.T
print("Matrix with none transposition: \n",matriz)
print("Matrix with transposition: \n",matriz.T)

Matrix with none transposition: 
 [[1 2]
 [3 4]
 [5 6]]
Matrix with transposition: 
 [[1 3 5]
 [2 4 6]]


In [102]:
matrixTwo=np.array([[1],[2]])
print(matrixTwo.shape)

(2, 1)


In [103]:
print(matriz.shape)

(3, 2)


In [104]:
print(matriz_t.shape)

(2, 3)


In [107]:
tensor_t=tensor.T
print("Tensor none transposite: \n",tensor)
print("Tensor transposite: \n", tensor_t)

Tensor none transposite: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 6  7  8]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
Tensor transposite: 
 [[[ 1 11 21]
  [ 4 14 24]
  [ 6 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 7 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 8 19 29]]]


In [118]:
escalar = 5.679
vector = np.array([3,4,5,61])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor=np.array([
    [[1,2,3,30],[4,5,6,31],[17,18,19,35]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[27,28,29,38]],
])

In [119]:
escalar_t=escalar.T

AttributeError: 'float' object has no attribute 'T'

In [121]:
vector_t=vector.T
print(vector_t)

[ 3  4  5 61]


In [123]:
matriz_t=matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [124]:
print(matriz_t.shape)

(2, 3)


In [125]:
print(matriz.shape)

(3, 2)


In [126]:
tensor_t=tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [17 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [18 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [19 19 29]]

 [[30 33 36]
  [31 34 37]
  [35 35 38]]]


In [127]:
print(tensor)

[[[ 1  2  3 30]
  [ 4  5  6 31]
  [17 18 19 35]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]


In [129]:
#The trasnpuest form for another transpuest form to matrix is equal to matrix base#

In [133]:
matriz_t_t=matriz_t.T
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


In [134]:
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


In [135]:
#matrix´s sume#

In [138]:
A=matriz
B=matriz_t

In [139]:
C=A+B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [140]:
A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[6,5],[4,3],[2,1]])
C=A+B
print("Matrix A: \n", A,"\n")
print("Matrix B: \n", B,"\n")
print("Matrix C: \n", C,"\n")

Matrix A: 
 [[1 2]
 [3 4]
 [5 6]] 

Matrix B: 
 [[6 5]
 [4 3]
 [2 1]] 

Matrix C: 
 [[7 7]
 [7 7]
 [7 7]] 



In [144]:
D=matriz+escalar
print(escalar)

5.679


In [143]:
print("Sume´s matrix with scalar number: \n", D)

Sume´s matrix with scalar number: 
 [[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]


In [145]:
matrixFiveXFive=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(matrixFiveXFive)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [146]:
matrixFiveXFive_t=matrixFiveXFive.T
print(matrixFiveXFive_t)

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


In [147]:
sumeOfTheseMatrix=matrixFiveXFive+matrixFiveXFive_t
print(sumeOfTheseMatrix)

[[ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]
