In [1]:
import numpy as np

In [5]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    array([[1.

In [7]:
matriz = np.identity(3)
matriz

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
print(matriz[:,0].dot(matriz[:,1]))

0.0


In [13]:
print(matriz[:,0].dot(matriz[:,2]))

0.0


In [15]:
print(matriz[:,1].dot(matriz[:,2]))

0.0


In [18]:
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))

1.0
1.0
1.0


In [19]:
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0.0
0.0
0.0


In [24]:
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


In [28]:
A = np.array([[np.cos(100), -np.sin(100)],
             [np.sin(100),np.cos(100)]])
A

array([[ 0.86231887,  0.50636564],
       [-0.50636564,  0.86231887]])

In [31]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [34]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


In [36]:
A_t = A.T
print(A_t.dot(A))
print(A.dot(A_t))

[[ 1.00000000e+00 -7.93771519e-18]
 [-7.93771519e-18  1.00000000e+00]]
[[1.00000000e+00 7.93771519e-18]
 [7.93771519e-18 1.00000000e+00]]


In [37]:
A_t

array([[ 0.86231887, -0.50636564],
       [ 0.50636564,  0.86231887]])

In [39]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [40]:
print(1/A_t.dot(A))

[[ 1.00000000e+00 -1.25980837e+17]
 [-1.25980837e+17  1.00000000e+00]]
