In [1]:
import numpy as np

In [ ]:
identidad = np.eye(4)

In [ ]:
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
vector=np.array([[2],[3],[5],[7]])

In [ ]:
print(identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


In [ ]:
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [ ]:
A = np.array ([[1,0,1], [0,1,1], [-1,1,1]]) 
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [ ]:
inversa_A = np.linalg.inv(A)

In [11]:
print(inversa_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [12]:
print(A.dot(inversa_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
singular = np.array ([[1,1], [1,1]])
#Cuando no existe matriz inversa se le llama matriz singular

### Cuando no existe la inversa la llamamos matriz singular.

In [5]:
print(singular)

[[1 1]
 [1 1]]


[[3 1]
 [2 1]]
