In [1]:
import numpy as np

In [3]:
escalar = 5.679    
vector = np.array ([2,3])
matriz =np.array([[1,2],[3,4], [5,6]])

In [4]:
A=matriz*vector

In [5]:
B=matriz.dot(vector)#Producto interno#

In [6]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [7]:
print(B)

[ 8 18 28]


In [8]:
B=matriz.dot(vector)
C= np.dot(matriz, vector)
print(B)
print(C)

[ 8 18 28]
[ 8 18 28]


In [15]:
# Challenge #
vectorTwo= np.array([1,2])
matrixTwo=np.array([[1,5],[6,8],[9,10]])
print(vectorTwo)
print(matrixTwo)

[1 2]
[[ 1  5]
 [ 6  8]
 [ 9 10]]


In [14]:
C=matrixTwo.dot(vectorTwo)
D=np.dot(matrixTwo,vectorTwo)
print(C)
print(D)

[11 22 29]
[11 22 29]
