In [1]:
import numpy as np

In [5]:
A=np.array ([[2,3], [5,7], [11,13]])
B=np.array ([[1,3], [2,1]])
C=np.array([[3,1],[4,2]])

In [7]:
# Asociativa
ABC=A.dot(B.dot(C))
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [8]:
AB_C=A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


In [9]:
#Distributiva
D=A.dot(B+C)
E=(A.dot(B)+(A.dot(C)))
print(D)
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [10]:
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [17]:
#Multiplicación de matrices no es conmutativa
F=B.dot(C)

In [12]:
G=C.dot(B)

In [13]:
print(F==G)

[[False False]
 [False False]]


In [15]:
print(F)

[[15  7]
 [10  4]]


In [16]:
print(G)

[[ 5 10]
 [ 8 14]]


In [18]:
#Multiplicación de véctores si es conmutativa

In [19]:
v1=np.array([[2],[7]])
v2=np.array([[3],[5]])

In [20]:
v1_tv2=v1.T.dot(v2)
v2_tv1=v2.T.dot(v1)

In [21]:
print(v1_tv2)

[[41]]


In [22]:
print(v2_tv1)

[[41]]


In [24]:
#Challenge´s class
matrixOne=np.array([[5,4,9],[9,7,8],[10,48,7],[1,4,9]])
matrixTwo=np.array([[5,6],[7,9],[10,5]])

In [25]:
matrixProduct=matrixOne.dot(matrixTwo)

In [26]:
print(matrixProduct)

[[143 111]
 [174 157]
 [456 527]
 [123  87]]
