In [1]:
import numpy as np

In [2]:
escalar = 5.679         
vector =  np.array([3,
                    4,
                    5])
matriz = np.array([[1,2],
                   [3,4],
                   [5,6]])

In [3]:
A = vector+matriz

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [5]:
# Broadcasting #
A = matriz.T+vector
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [6]:
C=matriz+42

In [7]:
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [10]:
D = matriz + np.array([[42],
                       [42],
                       [42]])
print(D)

[[43 44]
 [45 46]
 [47 48]]


In [14]:
# Challenge #
Vector=np.array([1,2,3,4,5])
matrix=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [12]:
sume=Vector+matrix

In [13]:
print(sume)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]]
