In [1]:
import numpy as np

### Norma 0.- items distintos de 0.

In [4]:
vector = np.array([1-50,-25,0,25,100,-300])

print(np.linalg.norm(vector, ord=0))

5.0


### Norma 1.- la suma absoluta de todos los valores del vector

In [5]:
vector = np.array([1,-1,1,-1,1])
vector

array([ 1, -1,  1, -1,  1])

In [6]:
print(np.linalg.norm(vector, ord=1))

5.0


In [6]:
v = np.array([7,-7,3])
u = np.array([1,1,0])
w = np.array([0,0,1])

print(np.linalg.norm(v, ord=1))
print(np.linalg.norm(u, ord=1))
print(np.linalg.norm(w, ord=1))

17.0
2.0
1.0


### Norma 2.- distancia euchidiana (módulo)

In [2]:
vector = np.array([1/2,1/2,1/2,1/2])
vector

array([0.5, 0.5, 0.5, 0.5])

In [3]:
print(np.linalg.norm(vector))
print(np.linalg.norm(vector, ord = 2))

1.0
1.0


### Norma L^2.- calcula los valores al cuadrado

In [14]:
vector = np.array([1,1])
print(vector)
print(np.linalg.norm(vector, ord=2)**2)

[1 1]
2.0000000000000004


In [16]:
print(vector.T.dot(vector))

2


In [22]:
# a = np.array([[1, 0], [0,1]])
# b = np.array([[4, 1], [2,2]])
# np.dot(a,b) == a*b

In [23]:
# a * b

### Norma infinito

In [24]:
vector = np.array([1,2,3,-100])
vector

array([   1,    2,    3, -100])

In [25]:
print(np.linalg.norm(vector, ord=np.inf))

100.0
