In [1]:
import numpy as np
import pandas as pd

In [8]:
data = np.linspace(0,12,13)
data

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [12]:
np.matrix((3,4), int)

matrix([[3, 4]])

In [11]:
array = np.empty((2, 3), int)
array

array([[47976016,        0,        0],
       [       0,        0,        0]])

In [19]:
array = np.linspace(1,12,12)
array = array.reshape(3,4).T
array.shape

(4, 3)